### ISSUE TITLE
Calling forecasting contract fallback function with a number?

### ISSUE THREAD

**Issue by stefek99** [WingsDao/wings-integration#21]
https://github.com/WingsDao/wings-integration/blob/master/contracts/BasicCrowdsale.sol#L22-L34
```
  // called by CrowdsaleController to transfer reward part of ETH
  // collected by successful crowdsale to Forecasting contract.
  // This call is made upon closing successful crowdfunding process
  // iff agreed ETH reward part is not zero
  function mintETHRewards(
    address _contract,  // Forecasting contract
    uint256 _amount     // agreed part of totalCollected which is intended for rewards
  )
    public
    onlyManager() // manager is CrowdsaleController instance
  {
    require(_contract.call.value(_amount)());
  }
```

Quick search: https://ethereum.stackexchange.com/questions/6391/what-does-call-value-mean-and-how-did-it-allow-the-attack-to-the-dao

> `contract.call.value(...)()` will [invoke](https://ethereum.stackexchange.com/questions/1585/why-does-an-empty-message-still-invoke-the-code-of-the-contrac) the [fallback function](https://ethereum.stackexchange.com/questions/5992/how-much-computation-can-be-done-in-a-fallback-function) at `contract` with almost all the gas that the caller has.  In a normal call like `contract.foo`, if `contract` is untrusted, it is much clearer that untrusted code (`foo`) is explicitly being invoked.

Also similar to #20, we may want to consider a `whenCrowdsaleSuccessful()` modifier.

**Comment by RomanFro** [comment]
Related to https://github.com/WingsDao/wings-integration/issues/20#issuecomment-378267669
